---
packages:
- name: ruby
  version: !binary |-
    NTcyYTlkMzU4OWE3NGUwNDRiMTk1YWQwNzc4ZjdkNjYxMTdiZjk4Yw==
  sha1: !binary |-
    MWY3ZmJkZTljYzdmMDNjNzc1Nzg2MzBmNjg3YTNlMTU1MDI4YTMyOA==
  fingerprint: !binary |-
    NTcyYTlkMzU4OWE3NGUwNDRiMTk1YWQwNzc4ZjdkNjYxMTdiZjk4Yw==
  dependencies: []
- name: mongodb
  version: !binary |-
    OTgyNTg5ZWFlY2JhNzAyMDk1ZTdiZjA0ZjQ0YTg1NTY1ZGZkNmYwYg==
  sha1: !binary |-
    YTIyNTUxM2NhY2FkZTkwNTVjYjI5MWQyMjY5OWRkMzEyMmJkMzM2Nw==
  fingerprint: !binary |-
    OTgyNTg5ZWFlY2JhNzAyMDk1ZTdiZjA0ZjQ0YTg1NTY1ZGZkNmYwYg==
  dependencies: []
- name: riemann-mongodb
  version: !binary |-
    NmM2MzEwZTc3OWQwMzIyY2VhN2UwZWQ3YzU0YzhiZDYwNGE3NGQxMQ==
  sha1: !binary |-
    MTJmMzQxOGNhMmRiOGVkNzczNDAwZTRiNjczOTRiM2QxM2E1MjkzZA==
  fingerprint: !binary |-
    NmM2MzEwZTc3OWQwMzIyY2VhN2UwZWQ3YzU0YzhiZDYwNGE3NGQxMQ==
  dependencies:
  - ruby
jobs:
- name: replset
  version: !binary |-
    MzkxZTFkY2I0OGRjMGNmMzlkMzNkM2E2YTVjMDRkNTRhMDE2ZTQzZQ==
  fingerprint: !binary |-
    MzkxZTFkY2I0OGRjMGNmMzlkMzNkM2E2YTVjMDRkNTRhMDE2ZTQzZQ==
  sha1: !binary |-
    NjI2Y2JhMTUzODE4OTRiYjA1MGM5NGY2MmQ2MzkxNjM1ODYwMzU3OA==
- name: mongodb
  version: !binary |-
    MzRlMzM5ODRhMDRiYmMwYmYwMDI3ZTE5OTg4MGIzZTBlMjQ3NTdkZg==
  fingerprint: !binary |-
    MzRlMzM5ODRhMDRiYmMwYmYwMDI3ZTE5OTg4MGIzZTBlMjQ3NTdkZg==
  sha1: !binary |-
    Mzg3YzY3ODMyNWY1ODg2ZTVlYzg0MjE0Yjg1ODAxY2UzMDRjNmJjYg==
- name: riemann-mongodb
  version: !binary |-
    Y2JmYTVmNzAyZWNhMTc4NDU5YmFkMjA3NDQwMjg4MzIyZjY0NzdiNg==
  fingerprint: !binary |-
    Y2JmYTVmNzAyZWNhMTc4NDU5YmFkMjA3NDQwMjg4MzIyZjY0NzdiNg==
  sha1: !binary |-
    OTA0MzJiOTY3MGMxYjdlYTYxYzk5YmI0NDI2ZTc0MGI1NTE5M2NkZA==
commit_hash: c4af0f36
uncommitted_changes: true
name: mongodb-hybris
version: 9
