---
packages:
- name: mongodb
  version: !binary |-
    OTgyNTg5ZWFlY2JhNzAyMDk1ZTdiZjA0ZjQ0YTg1NTY1ZGZkNmYwYg==
  sha1: !binary |-
    Mjg0MWE5YzA1MzdlOGMyMjZhMWFhYzk0MDNjYzgwNTI0NmU0YzgwZg==
  fingerprint: !binary |-
    OTgyNTg5ZWFlY2JhNzAyMDk1ZTdiZjA0ZjQ0YTg1NTY1ZGZkNmYwYg==
  dependencies: []
jobs:
- name: replset
  version: !binary |-
    N2ViNzJkZTVjMzAyOWE1NDE4OGM4M2Q4NTU0ZmNiYmJlNWM1OTI0MA==
  fingerprint: !binary |-
    N2ViNzJkZTVjMzAyOWE1NDE4OGM4M2Q4NTU0ZmNiYmJlNWM1OTI0MA==
  sha1: !binary |-
    MDhiYzVkZGY4MGEzZjdiMjA5MTYzMTg3YjhlYTg0ZWNkN2VjZTE1NA==
- name: mongodb
  version: !binary |-
    NjZjZjMyZWMwZDdlYmEyOWExZWU3ZjVkOTkxODcyMTcxZjJkY2I2NA==
  fingerprint: !binary |-
    NjZjZjMyZWMwZDdlYmEyOWExZWU3ZjVkOTkxODcyMTcxZjJkY2I2NA==
  sha1: !binary |-
    YmMxZTAwNzQ2NGZmZDNhOGNmZTEwMGUwOThhNmU5NmRlYzRmMzFiOQ==
commit_hash: 2b809bc2
uncommitted_changes: true
name: mongodb-hybris
version: '15'
