---
name: mongodb-aws-ec2-us-staged
director_uuid: c2c7b674-fdf8-4ded-922c-1b94ae9a62c2

meta:
  environment: mongodb-dev
  stemcell:
    name: bosh-aws-xen-ubuntu
    version: latest

releases:
  - name: mongodb-hybris
    version: latest

compilation:
  reuse_compilation_vms: true
  workers: 3
  network: us-east-1d
  cloud_properties:
    availability_zone: us-east-1d
    instance_type: c1.medium

update:
  canaries: 1
  canary_watch_time: 30000-240000
  update_watch_time: 30000-600000
  max_in_flight: 1
  serial: false

properties: {}

resource_pools:
  - name: mongodb-us-east-1d
    stemcell:
      name: bosh-aws-xen-ubuntu
      version: latest
    network: us-east-1d
    size: 7
    cloud_properties:
      instance_type: m1.medium
      availability_zone: us-east-1d

  - name: mongodb-us-east-1c
    stemcell:
      name: bosh-aws-xen-ubuntu
      version: latest
    network: us-east-1c
    size: 6
    cloud_properties:
      instance_type: m1.medium
      availability_zone: us-east-1c

networks:
  - name: us-east-1d
    type: manual
    subnets:
      - cloud_properties:
          security_groups:
            - mongoDB
          subnet: subnet-1bc0cb5d
        dns:
          - 10.10.0.2
        gateway: 10.10.122.1
        name: default_unused
        range: 10.10.122.0/24
        reserved:
          - 10.10.122.2 - 10.10.122.9
        static:
          - 10.10.122.10 - 10.10.122.50

  - name: us-east-1c
    type: manual
    subnets:
      - cloud_properties:
          security_groups:
            - mongoDB
          subnet: subnet-55a14a22
        dns:
          - 10.10.0.2
        gateway: 10.10.125.1
        name: default_unused
        range: 10.10.125.0/24
        reserved:
          - 10.10.125.2 - 10.10.125.9
        static:
          - 10.10.125.10 - 10.10.125.50

jobs:
  ############ REGISTRY REPLICA SET ############
  - name: mongodb_staged_registry_z1
    instances: 2
    templates:
      - name: mongodb
    resource_pool: mongodb-us-east-1d
    persistent_disk: 256000
    networks:
      - name: us-east-1d
        static_ips:
          - 10.10.122.10
          - 10.10.122.11
    properties:
      mongodb:
        replSet:
          name: "mongodb-staged-rs-registry"

  - name: mongodb_staged_registry_z2
    instances: 2
    templates:
      - name: mongodb
    resource_pool: mongodb-us-east-1c
    persistent_disk: 256000
    networks:
      - name: us-east-1c
        static_ips:
          - 10.10.125.10
          - 10.10.125.11
    properties:
      mongodb:
        replSet:
          name: "mongodb-staged-rs-registry"

  ############ DATA 1 REPLICA SET ############
  - name: mongodb_staged_data1_z1
    instances: 2
    templates:
      - name: mongodb
    resource_pool: mongodb-us-east-1d
    persistent_disk: 256000
    networks:
      - name: us-east-1d
        static_ips:
          - 10.10.122.12
          - 10.10.122.13
    properties:
      mongodb:
        replSet:
          name: "mongodb-staged-rs-data1"

  - name: mongodb_staged_data1_z2
    instances: 2
    templates:
      - name: mongodb
    resource_pool: mongodb-us-east-1c
    persistent_disk: 256000
    networks:
      - name: us-east-1c
        static_ips:
          - 10.10.125.12
          - 10.10.125.13
    properties:
      mongodb:
        replSet:
          name: "mongodb-staged-rs-data1"

  ############ DATA 2 REPLICA SET ############
  - name: mongodb_staged_data2_z1
    instances: 2
    templates:
      - name: mongodb
    resource_pool: mongodb-us-east-1d
    persistent_disk: 256000
    networks:
      - name: us-east-1d
        static_ips:
          - 10.10.122.14
          - 10.10.122.15
    properties:
      mongodb:
        replSet:
          name: "mongodb-staged-rs-data2"

  - name: mongodb_staged_data2_z2
    instances: 2
    templates:
      - name: mongodb
    resource_pool: mongodb-us-east-1c
    persistent_disk: 256000
    networks:
      - name: us-east-1c
        static_ips:
          - 10.10.125.14
          - 10.10.125.15
    properties:
      mongodb:
        replSet:
          name: "mongodb-staged-rs-data2"

  # bosh run errand
  - name: mongodb_staged_rs
    instances: 1
    template: replset
    lifecycle: errand
    resource_pool: mongodb-us-east-1d
    networks:
      - name: us-east-1d
    properties:
      mongodb:
        replSet:
          - name: "mongodb-staged-rs-regisry"
            members:
              - 10.10.122.10
              - 10.10.122.11
              - 10.10.125.10
              - 10.10.125.11
          - name: "mongodb-staged-rs-data1"
            members:
              - 10.10.122.12
              - 10.10.122.13
              - 10.10.125.12
              - 10.10.125.13
          - name: "mongodb-staged-rs-data2"
            members:
              - 10.10.122.14
              - 10.10.122.15
              - 10.10.125.14
              - 10.10.125.15
